FROM --platform=$TARGETPLATFORM golang:1.13-buster as builder

RUN set -ex \
    && apt-get update && apt-get install -y --no-install-recommends \
        libsystemd-dev

WORKDIR $GOPATH/src/github.com/box/kube-iptables-tailer
COPY . $GOPATH/src/github.com/box/kube-iptables-tailer
RUN make build-cgo

FROM --platform=$TARGETPLATFORM debian:buster-slim

WORKDIR /root/
COPY --from=builder /go/src/github.com/box/kube-iptables-tailer/kube-iptables-tailer /kube-iptables-tailer
CMD ["/kube-iptables-tailer"]
